esphome:
  platformio_options:
    upload_speed: 921600

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

ota:

wifi:
  ssid: !secret wifi_ssid 
  password: !secret wifi_password
  fast_connect: true

substitutions:
  LOG_LEVEL: INFO

# Enable logging
logger:
  level: ${LOG_LEVEL}

# Enable Home Assistant API
api:
  password: ""

time:
  - platform: homeassistant
    id: esptime